In [1]:
import pandas as pd

In [3]:
csv_file = "efw_cc.csv"
df_econForum = pd.read_csv(csv_file)
df_econForum.head()

,year,ISO_code,countries,ECONOMIC FREEDOM,rank,quartile,1a_government_consumption,1b_transfers,1c_gov_enterprises,1d_top_marg_tax_rate,...,3_sound_money,4a_tariffs,4b_regulatory_trade_barriers,4c_black_market,4d_control_movement_capital_ppl,4_trade,5a_credit_market_reg,5b_labor_market_reg,5c_business_reg,5_regulation
0,2016,ALB,Albania,7.54,34.0,1.0,8.232353,7.509902,8.0,8.0,...,9.553657,8.963556,7.489905,10.00000,6.406138,8.214900,7.098562,6.916278,6.705863,6.906901
1,2016,DZA,Algeria,4.99,159.0,4.0,2.150000,7.817129,0.0,4.5,...,7.253894,6.872533,2.481294,5.56391,1.590362,4.127025,5.100509,5.029513,5.676956,5.268992
2,2016,AGO,Angola,5.17,155.0,4.0,7.600000,8.886739,0.0,9.5,...,5.606605,6.989244,2.024949,10.00000,2.044823,5.264754,7.064905,4.560325,4.930271,5.518500
3,2016,ARG,Argentina,4.84,160.0,4.0,5.335294,6.048930,6.0,4.0,...,5.614336,6.421600,4.811105,0.00000,4.697482,3.982547,5.419820,5.151405,5.535831,5.369019
4,2016,ARM,Armenia,7.57,29.0,1.0,7.264706,7.748532,8.0,5.0,...,9.521940,8.547556,7.194410,10.00000,6.830998,8.143241,9.102046,6.234630,6.797530,7.378069

In [5]:
df_econForum.dtypes.head()

year                  int64
ISO_code             object
countries            object
ECONOMIC FREEDOM    float64
rank                float64
dtype: object

In [7]:
df_countries = df_econForum[['countries', 'ECONOMIC FREEDOM']]
df_countries.dropna()

                   countries  ECONOMIC FREEDOM
0                    Albania              7.54
1                    Algeria              4.99
2                     Angola              5.17
3                  Argentina              4.84
4                    Armenia              7.57
5                  Australia              7.98
6                    Austria              7.58
7                 Azerbaijan              6.49
8                    Bahamas              7.34
9                    Bahrain              7.56
10                Bangladesh              6.30
11                  Barbados              6.43
12                   Belarus              6.23
13                   Belgium              7.32
14                    Belize              6.86
15                     Benin              5.98
16                    Bhutan              7.02
17                   Bolivia              6.23
18    Bosnia and Herzegovina              6.60
19                  Botswana              7.43
20                    Brazil              5.75
21         Brunei Darussalam              6.93
22                  Bulgaria              7.41
23              Burkina Faso              6.05
24                   Burundi              5.92
25                  Cambodia              7.17
26                  Cameroon              5.82
27                    Canada              7.98
28                Cape Verde              6.68
29         Central Afr. Rep.              5.11
...                      ...               ...
3638                   Japan              7.68
3641                   Kenya              5.11
3642            Korea, South              5.84
3652              Luxembourg              8.01
3654              Madagascar              5.43
3656                Malaysia              6.25
3661                  Mexico              6.78
3665                 Morocco              4.74
3670             Netherlands              7.01
3671             New Zealand              6.62
3674                 Nigeria              4.28
3675                  Norway              6.19
3677                Pakistan              4.45
3681                    Peru              4.62
3682             Philippines              5.30
3684                Portugal              5.51
3694               Singapore              7.08
3697            South Africa              5.91
3698                   Spain              6.12
3703                  Sweden              5.31
3704             Switzerland              7.41
3705                   Syria              4.61
3706                  Taiwan              6.40
3708                Tanzania              4.36
3709                Thailand              6.20
3713                 Tunisia              4.44
3714                  Turkey              3.52
3718          United Kingdom              5.94
3719           United States              7.77
3721               Venezuela              7.18

[3003 rows x 2 columns]